# Generated by Django 5.2.8 on 2025-11-21 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_funcionarios'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefatos',
            name='imagem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image'),
        ),
    ]
