# Generated by Django 5.2.8 on 2025-11-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_artefatos_imagem'),
        ('core', '0008_localizacao_artefatos_localizacao'),
    ]

    operations = [
    ]
