# Generated by Django 5.2.8 on 2025-11-21 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20251121_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefatos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categorias'),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='colecoes',
            field=models.ManyToManyField(blank=True, to='core.colecoes'),
        ),
    ]
