# Generated by Django 5.2.8 on 2025-11-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_artefatos_categoria_funcionarios_colecoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.CharField(blank=True, help_text='Passage ID', max_length=255, null=True, unique=True, verbose_name='passage_id'),
        ),
    ]
