# Generated by Django 5.2.8 on 2025-11-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_passage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefatos',
            name='categoria_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='colecao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='detalhe_conservacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='dimensoes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='estante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='grupo_etnico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='integridade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='nivel_conservacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='observacoes_gerais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='peso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='prateleira',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='sala',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='sitio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artefatos',
            name='subtipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artefatos',
            name='imagem',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='artefatos/'),
        ),
    ]
