# Generated by Django 5.2.8 on 2025-11-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_artefatos_categoria_nome_artefatos_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacao',
            name='bloco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='sitio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
